### PR TITLE
Segment container

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
@ncw Ping ? :-)

**Comment by majewsky** [comment]
Looks good to me. @ncw @lebauce What's the timeline for bringing all of this into master?

**Comment by majewsky** [comment]
Oh, @lebauce, seeing how you move the `getAllSegments` operation down from the Docker Registry into here, can you see if you can integrate https://github.com/docker/distribution/pull/1605 into this?

**Comment by cezarsa** [comment]
Hey guys, if there are no objections I'd like to tackle this and finish the work started in this PR. @majewsky Regarding DLO's I can integrate the changes in docker/distribution#1605, docker/distribution#1650 and docker/distribution#1710. On the SLO side I'm not sure whether it's already working correctly or if there's still some work to be done, I'll try it and see.

I'll also start integrating the updated swift library into a fork of docker/distribution in preparation for a PR once this is all merged.

@ncw Is there anything else you'd like to see here to have this merged on master?

**Comment by swill** [comment]
Been waiting for this PR for quite a while now.  Is there a reason for the holdup?

**Comment by cezarsa** [comment]
@swill, I continued and finished the work to get segmentation up and running on #74. However I still haven't heard back from @ncw either. :(

That said, I've been running my fork of docker distribution using the code from #74 in production for about 4 months now and it's working perfectly. It creates SLOs by default and fallback to DLOs if the former isn't supported by the server.

I'd love to see this merged and I'm open to make any further changes to the code if the maintainers see it necessary. Just let me know, please.

**Comment by cezarsa** [comment]
Good news, @ncw reached out and offered to make me a collaborator to help maintain this project. I humbly accepted and will do my best helping out, starting with taking a look at open pull requests.

I'm closing this now in favor of #74 which was merged and already includes all commits from this PR.
Thank you guys for working on it.

**Pull request closed without merging**
