### PR TITLE
Issue #145 obviously it is a typo that the dstContainer should be srcContainer

### PR DESCRIPTION
**Pull request by 4xicom**
In object move, the original object should be get from srcContainer. It is a typo here.

### CODE REVIEW

**Comment by ncw** [comment]
Can you see if you can make a test that fails without the change but passes with it?

**Comment by 4xicom** [comment]
Added test cases for large object create move and delete base on in mem swift server in swifttest

**Comment by ncw** [comment]
Thank you for doing that - that is a brilliant piece of work :-)

**Comment by ncw** [comment]
I've made a release v1.0.48 with that in.

**Pull request merged**
