### PR TITLE
Add support for dynamic large object to the test server

### PR DESCRIPTION
**Pull request by lebauce**
Add support for Dynamic Large Object to the test server

### CODE REVIEW

**Comment by ncw** [comment]
You could quite easily make the server do a static large object too I think...

Are you planning to add some tests for large object support into `swift_test.go`?  That would mean that the functionality gets exercised in the test server, and when the unit tests are run against real servers that will find bugs in them too ;-)

**Comment by ncw** [comment]
re content-length: I just verified that you are correct - thanks!

**Comment by lebauce** [comment]
You're right, support for static large objects should be quite easy

**Comment by ncw** [comment]
I've merged the code above (I squashed some of the commits).  I had to fix the tests for running against a real server.

Can you do any further work in a new pull request please?

Great work on the docker repository :-)

Thanks for a super contribution

-- Nick

**Pull request closed without merging**
