### PR TITLE
Change Michel Couillard email

### PR DESCRIPTION
**Pull request by hexadecy**

### CODE REVIEW

**Comment by ncw** [comment]
We use this script https://github.com/ncw/swift/blob/master/bin/update-authors.py to update the authors from the git log, which means if I merge your patch then it will immedately add your old email address back in!

Not quite sure what to do about that - any suggestions?

**Comment by hexadecy** [comment]
https://help.github.com/articles/changing-author-info/

**Comment by ncw** [comment]
> https://help.github.com/articles/changing-author-info/

Alas that will break everyone who pulls this repo...

I was thinking more of a patch to the python program, or you could leave your old email address in the file.

**Comment by hexadecy** [comment]
Maybe just keep our names, but nor our emails.

**Comment by ncw** [comment]
> Maybe just keep our names, but not our emails.

Would it be OK if the file said something like this?

Michel Couillard (old: <old@email.com>) <new@email.com>

That would be fine with the automation.

PS Something has gone wrong with your push :-(  Can you rebase on master and force push to correct?

**Comment by hexadecy** [comment]
I modified the python script regex to skip the first `<!--`
So it will match the inner email `<!--<couillard.michel@voxlog.ca>-->`, but it won't de displayed in markdown.

**Comment by ncw** [comment]
That is great - thank you.  I never would have thought of using a negative look-behind assertion - very clever :-)

**Pull request merged**
