### PR TITLE
SLO multipart manifest

### PR DESCRIPTION
**Pull request by lebauce**
Those 2 commits add minimal support for static large objects but allowing upload of a JSON manifest and retrieving its content.

### CODE REVIEW

**Comment by lebauce** [comment]
Ping @ncw :-)

**Comment by ncw** [comment]
@lebauce very sorry I have been so slow at looking at this.

The functionality looks fine, but I'm not a big fan of the `X-Static-Large-Object` approach in the extra headers.

Perhaps a better approach might be to rename `ObjectOpen` to `objectOpen` and add an extra parameter `parameters url.Values` to it.  `ObjectOpen` would then call `objectOpen`.

You could then build some higher level functions on the top to access the manifests, eg `ObjectOpenManifest` and `ObjectCreateManifest` or something like that.

What do you think?

**Comment by nevermosby** [comment]
Hi @lebauce long time no see. I believe this PR is related to [the PR for docker distribution](https://github.com/docker/distribution/pull/1438) which is about to use the new interface of StorageDriver.
So you are working on the swift driver update for that, right?

**Comment by lebauce** [comment]
@nevermosby Hey ! Yes, it's related. I would like the Static Large Object and Dynamic Large Object support to be directly in the library instead of being in the docker/distribution driver

**Comment by lebauce** [comment]
@ncw I do agree, it was an horrible hack.
I rewrote my PR, could you please take an other look ?

**Comment by ncw** [comment]
That looks great thanks @lebauce.  I'll try to find the time to review it this evening.  Thanks  Nick

**Comment by ncw** [comment]
...in the mean time can you have a look see why the tests failed on travis?

**Comment by lebauce** [comment]
Fixed the testsuite

**Comment by lebauce** [comment]
@ncw Added an `ObjectType` attribute to the `Object` struct and methods for moving large objects

**Comment by ncw** [comment]
I've created a new branch `large-objects` with your code which I've rebased, gofmted, tested and added docs.  I've also changed the interface slightly as you'll see from the commits - passing in a struct to the large file create functions gives us wiggle room to change the interface in the future and it is a lot easier to read.

https://github.com/ncw/swift/tree/large-objects

I have some remaining questions though...
  * I think we need to add an interface to specify the container the segments are stored in.  This should probably default to `container + "_segments"` - what do you think?
  * The swift segment path doesn't seem to be the format as defined in [the docs](http://docs.openstack.org/developer/swift/overview_large_objects.html) - not sure if this really matters though!

**Comment by lebauce** [comment]
@ncw Thanks !

I do agree we need to add an interface to specify where to put the segments. The `LargeObjectOpts` may be a good fit, with a `Prefix` field for instance in the form of `container/prefix`. An other solution could be to allow specifying a callback that would accept two arguments `container` and a `objectName` and would return the path of the segment. What do you think ?

One little problem with this approach though is that the current code makes the assumption that the segments are in the same container than the object, but this can be easily fixed.
The other problem I see is that BulkDelete is used to delete the segments and the objects in one request and this method accepts a `container` argument when the Swift middleware really is able to delete objects from different containers at the same time. Speaking of which, the current `LargeObjectDelete` does 
```go
if false && len(objects) > 0 {
```
I would like to add a `BulkDeleteSupport` boolean that would be set after the first call to `QueryInfo` or set manually by the user if the server does not enable querying `/info`.

**Comment by ncw** [comment]
> I do agree we need to add an interface to specify where to put the segments. The LargeObjectOpts may be a good fit, with a Prefix field for instance in the form of container/prefix. An other solution could be to allow specifying a callback that would accept two arguments container and a objectName and would return the path of the segment. What do you think ?

I'd suggest we just keep it simple for the moment and have a `SegmentsContainer` field in `LargeObjectOpts` which can default to `Container + "_segments"`.  This will make it compatible with the `swift` tool.

The `LargeObjectOpts` gives us the chance to add more features later if we want.

> One little problem with this approach though is that the current code makes the assumption that the segments are in the same container than the object, but this can be easily fixed.

Shouldn't be too tricky!

As for BulkDelete - it should definitely be optional as there are still swift installations that don't support it (ours for instance!).

Are you happy to carry on sending pull requests against the `large-objects` branch?  I'll review and merge them there, then when we think we are done we can merge the feature to master.

Thanks 

Nick

**Comment by hroumani** [comment]
Wow I was debating doing something exactly like this (or at the application layer above this interface) but stumbled upon this pull request ;)

Any update on the status here, is it still being worked on ?

Looks great overall from taking a quick peek at the various proposed changes though.

**Comment by lebauce** [comment]
@hroumani A `large-objects` branch has been created on the main repository and I pushed a new version of them here https://github.com/ncw/swift/pull/66, but the are still under review by @ncw

**Comment by ncw** [comment]
@lebause - apologies for the veeeeery long delay ;-)

I've rebased and merged your code into the large objects branch.  It looks good and I think we should merge it ASAP!

I tried it against a server which doesn't support static large objects and I get this - can we skip these tests somehow?

```
=== RUN   TestSLOCreate
--- FAIL: TestSLOCreate (1.11s)
	swift_test.go:1794: Contents wrong
=== RUN   TestSLOInsert
--- FAIL: TestSLOInsert (0.68s)
	swift_test.go:1823: Contents wrong
=== RUN   TestSLOAppend
--- FAIL: TestSLOAppend (0.83s)
	swift_test.go:1856: Contents wrong
=== RUN   TestSLOMove
--- FAIL: TestSLOMove (0.02s)
	swift_test.go:1867: Not a large object
=== RUN   TestSLONoSegmentContainer
--- FAIL: TestSLONoSegmentContainer (1.52s)
	swift_test.go:1922: Contents wrong
```

**Comment by ncw** [comment]
I'm going to close this one as it is merged into the large-objects branch and will get merged as part of #66

**Pull request closed without merging**
