### PR TITLE
fix race between (*ObjectCreateFile).Write() and (*Connection).ObjectCreate()'s requesting goroutine

### PR DESCRIPTION
**Pull request by encryptio**
I had a deadlock issue in a virtualized testing environment (and thus with random latency spikes for both IO and CPU) while creating objects. By the time I realize it's locked up, the only goroutine running anything of note has this as its head of stack trace:

    2 @ 0x41f639 0x41f6bb 0x433700 0x47f8bd 0x4f271f 0x4f2b8f 0x575c4c 0x4f16eb 0x4bb8e3 0x4bded4 0x4bbb38 0x4b9ee3 0x4b9d78 0x4bcc12 0x4bbb38 0x4ba660 0x4ba413 0x4bd201 0x409f62 0x40a3c6 0x409a6e 0x40998c 0x409659 0x406ae8 0x405ef5 0x40164f 0x40119b 0x40a947 0x41f8d0
    #       0x433700        sync.runtime_Syncsemacquire+0xc0                                                        /home/croll/local/go-1.3.3/src/pkg/runtime/sema.goc:257
    #       0x47f8bd        sync.(*Cond).Wait+0x9d                                                                  /home/croll/local/go-1.3.3/src/pkg/sync/cond.go:62
    #       0x4f271f        io.(*pipe).write+0x21f                                                                  /home/croll/local/go-1.3.3/src/pkg/io/pipe.go:94
    #       0x4f2b8f        io.(*PipeWriter).Write+0x5f                                                             /home/croll/local/go-1.3.3/src/pkg/io/pipe.go:161
    #       0x575c4c        github.com/ncw/swift.(*ObjectCreateFile).Write+0x1cc                                    /$GOPATH/github.com/ncw/swift/swift.go:1062
    #       0x4f16eb        io.Copy+0x27b                                                                           /home/croll/local/go-1.3.3/src/pkg/io/io.go:355
    #       0x4bb8e3        mycompany/myproject/resource.swiftResource.Upload+0x503        /mycompany/myproject/resource/swift.go:160
    ...

I think this deadlock is caused by this race:

If `(*ObjectCreateFile).Write()` fails its nonblocking read on `file.done` (and thus passes through), it sends the byte string over to the pipeWriter half and to the hasher.
If during the same time, the request finishes unexpectedly (for example, due to a timeout), there's a time period in between that and the helper goroutine of `(*Connection).ObjectCreate()`'s call to `close(file.done)`. The `Write()` call has already made its check on `file.done`, and thus blocks forever waiting for a read on `file.pipeReader`.

This patch changes `(*Connection).ObjectCreate()`'s helper goroutine to close pipeReader when the request finishes in addition to closing `file.done`, and `(*ObjectCreateFile).Write()` is changed to use the `io.Pipe`'s signaling instead of `file.done`'s signaling. `file.done` is still neccessary to wait for completion of the request in `(*ObjectCreateFile).Close()`.

### CODE REVIEW

**Comment by encryptio** [comment]
This is a largely untested patch; any feedback is appreciated.

**Comment by ncw** [comment]
Thanks for taking the time to track the bug down and make a report.

The race is clear to me now you've pointed it out.

Your solution looks good - the idea of using the state of the Pipe to track whether it is closed is a good one.

I'd really like a test which fails with the old code but succeeds with the new.  Have you got time to do that? If not I'll do it in due course...

Thanks

Nick

**Comment by encryptio** [comment]
The only way I can think of to write a test case for this would be to have a fake swift api that waits for longer than the `(*Connection).Timeout` before reading data from the requester, and to have enough data in the pipe that it won't be buffered by TCP, then waiting for the timeout and ensuring that `(*ObjectCreateFile).Write()` returns. Fragile and sleep based ... I'm not sure how to make a *good* automated test case for it.

**Comment by ncw** [comment]
I agree with you - making a test for this race condition is rather tricky and liable to be fragile.

I've tested your patch with real servers and the race detector, and satisfied myself it has enough test coverage, so I've merged it as-is.

Thank you very much for your contribution - great detective work!

**Pull request merged**
