### PR TITLE
Add support for temporary URL

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by ncw** [comment]
Great feature thank you!

One of my test servers doesn't have the tempurl middleware which means the test fails on it.

I put in a bit of extra debugging to narrow the problem down.  It returns a 401 error.

```
--- FAIL: TestTempUrl (0.84s)
	swift_test.go:1471: HTTP Error retrieving file from temporary url 401
```

Do you have any ideas about how to detect features available in swift servers?  Is there a way of querying the swift middleware available remotely?

I've given you write access to the repo so you can push this to a branch on ncw/swift that we can collaborate on.

Thanks

Nick

```diff
diff --git a/swift_test.go b/swift_test.go
index 4ffe91b..6c44f46 100644
--- a/swift_test.go
+++ b/swift_test.go
@@ -1450,20 +1451,28 @@ func TestTempUrl(t *testing.T) {
 	}
 
 	_, headers, err := c.Account()
+	if err != nil {
+		t.Fatal(err)
+	}
 	m := headers.AccountMetadata()
 	m["temp-url-key"] = SECRET_KEY
 	err = c.AccountUpdate(m.AccountHeaders())
+	if err != nil {
+		t.Fatal(err)
+	}
 
 	expiresTime := time.Now().Add(20 * time.Minute)
 	tempUrl := c.ObjectTempUrl(CONTAINER, OBJECT, SECRET_KEY, "GET", expiresTime)
 	resp, err := http.Get(tempUrl)
-
 	if err != nil {
-		t.Error("Failed to retrieve file from temporary url")
+		t.Fatal("Failed to retrieve file from temporary url")
+	}
+	if resp.StatusCode != 200 {
+		t.Fatal("HTTP Error retrieving file from temporary url", resp.StatusCode)
 	}
 
 	if content, err := ioutil.ReadAll(resp.Body); err != nil || string(content) != CONTENTS {
-		t.Error("Bad content")
+		t.Error("Bad content", err)
 	}
 
 	resp.Body.Close()
```

**Comment by lebauce** [comment]
@ncw Thanks ! I pushed my branch to the repo. Are you going to add a new commit with your changes related to the extra debugging or should I add amend my commit ?

You can get the Swift configuration by querying the `/info` endpoint. I submitted a PR that adds a `QueryInfo` and return the JSON object of the configuration : https://github.com/ncw/swift/pull/46

As it can be disabled by the operator, the safest way to detect the feature is enabled is by creating a URL on an object - even a non existent one - and doing a HEAD on it. If it returns 200 or 404, the feature is present.

**Comment by ncw** [comment]
@lebauce I've added another commit to the branch which makes the tests run clean on a server with no tempurl support.  Not entirely happy with the solution but it works!

Can you review and if happy, squash the tempurl branch and merge it to master (with `--ff-only` by preference as I prefer to keep merge commits out of the history if possible).

Thanks

Nick

PS Thanks also for the `QueryInfo` - I'll review that shortly!

**Comment by lebauce** [comment]
@ncw I squashed the 2 commits of the `tempurl` and merge it into `master`. I hope I understood correctly :-/

**Comment by ncw** [comment]
@lebauce - perfect - thanks!

**Pull request closed without merging**
