### PR TITLE
Add QueryInfo method to discover Swift configuration

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by ncw** [comment]
This has been merged

**Comment by lebauce** [comment]
@ncw I think you closed this PR but you did not merge the `query-info` branch into `master`

**Comment by ncw** [comment]
Sorry, my fault - I didn't merge this at all did I!

I added a few notes on the request.

Also can you write a test for it?

Thanks

Nick

**Comment by lebauce** [comment]
ping @ncw :)

**Comment by ncw** [comment]
Sorry Sylvain - I completely missed this - thanks for the ping.

The tests look good - thanks.  I've merged this now.

Thanks

Nick

**Comment by lebauce** [comment]
@ncw No problem :) Thanks !

**Pull request closed without merging**
