### PR TITLE
Add symlink support

### LINKED ISSUE #139: Support for symlink
Hello,

First, a big thank you for this library <3.

I have a request though: could you support Symlink ? See https://github.com/openstack/swift/blob/master/swift/common/middleware/symlink.py

It's available since version 2.17 and i would be useful.

I tried to create an Object with `ObjectCreate`, the `X-Symlink-Target` header and a pseudo empty file (closed directly the file returned by ObjectCreate). But it's stored as just a plain empty file and not a symlink. It seems that the API wants a "nil" file instead of empty one ?

```go
      // [... init swift connexion to 's' variable]
       headers := map[string]string{
		"X-Symlink-Target": "container/myobject",
	}

	file, errC := s.ObjectCreate("container", "mysimlink", false, "", "application/octet-stream", headers)
	if errC != nil {
		return "", errC
	}

	// Empty file
	if err := file.Close(); err != nil {
		return "", err
	}
```

Note: my version of OpenStack: 2.18.1.dev68

### PR DESCRIPTION
**Pull request by thiagodasilva**
Added symlink support with tests. Dynamic links have been available in Swift
since version 2.17.0 and static links since 2.23.0

Closes #139

### CODE REVIEW

**Comment by ncw** [comment]
This looks like a nice contribution - thank you :-)

However the tests still need to pass on older swifts which don't support this feature.

Can you think of a way of doing that?

**Comment by thiagodasilva** [comment]
@ncw thank for taking a look! I tried to add a check on the /info endpoint. What do you think?

**Comment by ncw** [comment]
Looks like a great plan!  Do the tests still work when you try them on a swift backend with symlinks enabled?

I don't have access to a swift server like that... I wonder if there is a docker image for a swift all in one to test against - that would be really convenient and we could add that to the integration tests...

**Comment by thiagodasilva** [comment]
> Looks like a great plan! Do the tests still work when you try them on a swift backend with symlinks enabled?
yeah, worked for me. Although I wish I was able to get the skip messages printed out on terminal. That would tell me when tests are running or not
> 
> I don't have access to a swift server like that... I wonder if there is a docker image for a swift all in one to test against - that would be really convenient and we could add that to the integration tests...
Yeah, please try: `docker run -d -p 8080:8080 openstackswift/saio` 
This image is maintained by the openstack swift community. `latest` is tracking master, but there's also a tag for release 2.23

**Comment by ncw** [comment]
This looks great now thanks, I'll merge it.

> Yeah, please try: docker run -d -p 8080:8080 openstackswift/saio
This image is maintained by the openstack swift community. latest is tracking master, but there's also a tag for release 2.23

I've had a go with that with rclone and it works very well for testing.

It would be nice to set up a travis build which runs against that - fancy having a go at that?

**Pull request merged**
